# Generated by Django 5.0.1 on 2024-02-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_formpage_contactpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='intro',
            new_name='introduction',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
    ]
